---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1365']
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
        files: .*\.((x|ht|xht|zc)ml|pt)$
        types: [text]
      - id: debug-statements
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pycqa/isort
    rev: 5.6.4
    hooks:
      - id: isort
        additional_dependencies:
          - isort[pyproject]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [--config=.flake8]
        additional_dependencies:
          - flake8-blind-except
          - flake8-debugger
          - flake8-deprecated
          - flake8-mutable
          - flake8-pep3101
          - flake8-plone-hasattr
          - flake8-print
          - flake8-quotes
          - flake8-string-format
          - flake8-tidy-imports
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.7.3
    hooks:
      - id: pyupgrade
        args: [--py38-plus]
